package com.mamton.zoomalbum.data.local.file

import com.mamton.zoomalbum.core.math.Camera
import com.mamton.zoomalbum.domain.model.CanvasNode
import com.mamton.zoomalbum.domain.model.SceneGraph
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import javax.inject.Inject

class SceneGraphSerializer @Inject constructor() {

    private val json = Json {
        prettyPrint = true
        ignoreUnknownKeys = true
    }

    fun serialize(sceneGraph: SceneGraph): String = json.encodeToString(sceneGraph)

    fun deserialize(raw: String, albumId: Long): SceneGraph {
        // Migration: old format was a bare List<CanvasNode> (starts with '[').
        return if (raw.trimStart().startsWith('[')) {
            val parsed: JsonElement = json.parseToJsonElement(raw)
            val migratedNodes: JsonArray = migrateNodesArray(parsed as JsonArray)
            val nodes: List<CanvasNode> = json.decodeFromJsonElement(
                kotlinx.serialization.builtins.ListSerializer(CanvasNode.serializer()),
                migratedNodes,
            )
            SceneGraph(albumId = albumId, camera = Camera(), nodes = nodes)
        } else {
            val parsed: JsonElement = json.parseToJsonElement(raw)
            val migrated: JsonObject = migrateRootObject(parsed as JsonObject)
            json.decodeFromJsonElement(SceneGraph.serializer(), migrated)
        }
    }

    // ── Migration helpers ────────────────────────────────────────────────────
    //
    // Slice A appearance migration: legacy scene graphs stored `background`
    // directly on a FRAME node. The current model keeps it inside
    // `appearance.background`. We rewrite the JsonElement before decoding so
    // old albums load without losing their frame backgrounds.
    //
    // A FRAME node that already has `appearance` is left alone. A FRAME node
    // that has both (shouldn't happen — only one writer ever existed) prefers
    // the existing `appearance` and discards the legacy top-level field.

    private fun migrateRootObject(root: JsonObject): JsonObject {
        val nodes = root["nodes"] as? JsonArray ?: return root
        val migratedNodes = migrateNodesArray(nodes)
        if (migratedNodes === nodes) return root
        return buildJsonObject {
            for ((k, v) in root) {
                if (k == "nodes") put(k, migratedNodes) else put(k, v)
            }
        }
    }

    private fun migrateNodesArray(nodes: JsonArray): JsonArray {
        var changed = false
        val newNodes = nodes.map { element ->
            val obj = element as? JsonObject ?: return@map element
            // Only legacy frame nodes carried a top-level `background`; no other node type
            // ever had this field. Gating on key presence avoids depending on the on-disk
            // type discriminator, which is the FQCN (auto-generated by kotlinx-serialization)
            // and not a stable string.
            val legacyBackground = obj["background"] ?: return@map element
            if (obj.containsKey("appearance")) {
                // Both fields present — keep `appearance`, drop the legacy field.
                changed = true
                return@map buildJsonObject {
                    for ((k, v) in obj) if (k != "background") put(k, v)
                }
            }
            changed = true
            buildJsonObject {
                for ((k, v) in obj) {
                    if (k == "background") continue
                    put(k, v)
                }
                put(
                    "appearance",
                    buildJsonObject { put("background", legacyBackground) },
                )
            }
        }
        return if (changed) JsonArray(newNodes) else nodes
    }
}
