package com.mamton.zoomalbum.data.local.file

import com.mamton.zoomalbum.core.math.Camera
import com.mamton.zoomalbum.domain.model.CanvasNode
import com.mamton.zoomalbum.domain.model.SceneGraph
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import javax.inject.Inject

class SceneGraphSerializer @Inject constructor() {

    private val json = Json {
        prettyPrint = true
        ignoreUnknownKeys = true
    }

    fun serialize(sceneGraph: SceneGraph): String = json.encodeToString(sceneGraph)

    fun deserialize(raw: String, albumId: Long): SceneGraph {
        // Migration: old format was a bare List<CanvasNode> (starts with '[').
        return if (raw.trimStart().startsWith('[')) {
            val parsed: JsonElement = json.parseToJsonElement(raw)
            val migratedNodes: JsonArray = migrateNodesArray(parsed as JsonArray)
            val nodes: List<CanvasNode> = json.decodeFromJsonElement(
                kotlinx.serialization.builtins.ListSerializer(CanvasNode.serializer()),
                migratedNodes,
            )
            SceneGraph(albumId = albumId, camera = Camera(), nodes = nodes)
        } else {
            val parsed: JsonElement = json.parseToJsonElement(raw)
            val migrated: JsonObject = migrateRootObject(parsed as JsonObject)
            json.decodeFromJsonElement(SceneGraph.serializer(), migrated)
        }
    }

    // ── Migration helpers ────────────────────────────────────────────────────
    //
    // Slice A appearance migration: legacy scene graphs stored `background`
    // directly on a FRAME node. The current model keeps it inside
    // `appearance.background`. We rewrite the JsonElement before decoding so
    // old albums load without losing their frame backgrounds.
    //
    // Slice B overlay-field unification: legacy frame appearances stored their
    // overlay stack under `contentOverlays`. The unified model puts it under
    // `overlays` on the [NodeAppearance] base. We rename the key inside any
    // frame `appearance` object that has the legacy field but not the new one.
    // See `docs/architecture/appearance.md § 13`.

    private fun migrateRootObject(root: JsonObject): JsonObject {
        val nodes = root["nodes"] as? JsonArray ?: return root
        val migratedNodes = migrateNodesArray(nodes)
        if (migratedNodes === nodes) return root
        return buildJsonObject {
            for ((k, v) in root) {
                if (k == "nodes") put(k, migratedNodes) else put(k, v)
            }
        }
    }

    private fun migrateNodesArray(nodes: JsonArray): JsonArray {
        var changed = false
        val newNodes = nodes.map { element ->
            val obj = element as? JsonObject ?: return@map element
            val withBackground = migrateLegacyFrameBackground(obj)
            if (withBackground !== obj) changed = true
            val migrated = migrateAppearanceContentOverlays(withBackground)
            if (migrated !== withBackground) changed = true
            migrated
        }
        return if (changed) JsonArray(newNodes) else nodes
    }

    /**
     * Slice A: hoist legacy top-level `background` on a frame node into
     * `appearance.background`. A node that already has `appearance` keeps it
     * and the legacy top-level field is dropped.
     *
     * Only legacy frame nodes carried a top-level `background`; no other node
     * type ever had this field. Gating on key presence avoids depending on the
     * on-disk type discriminator (FQCN auto-generated by kotlinx-serialization,
     * not a stable string).
     */
    private fun migrateLegacyFrameBackground(obj: JsonObject): JsonObject {
        val legacyBackground = obj["background"] ?: return obj
        if (obj.containsKey("appearance")) {
            return buildJsonObject {
                for ((k, v) in obj) if (k != "background") put(k, v)
            }
        }
        return buildJsonObject {
            for ((k, v) in obj) {
                if (k == "background") continue
                put(k, v)
            }
            put(
                "appearance",
                buildJsonObject { put("background", legacyBackground) },
            )
        }
    }

    /**
     * Slice B: rename `appearance.contentOverlays` → `appearance.overlays` on
     * frame nodes. Only applies when `appearance` is a JSON object and the
     * legacy key is present while the new key is not. Same gating-on-key-
     * presence rule as Slice A — works regardless of the polymorphic
     * discriminator.
     */
    private fun migrateAppearanceContentOverlays(obj: JsonObject): JsonObject {
        val appearance = obj["appearance"] as? JsonObject ?: return obj
        val legacy = appearance["contentOverlays"] ?: return obj
        if (appearance.containsKey("overlays")) {
            // Both keys present — keep the new one, drop the legacy field.
            val rewrittenAppearance = buildJsonObject {
                for ((k, v) in appearance) if (k != "contentOverlays") put(k, v)
            }
            return buildJsonObject {
                for ((k, v) in obj) {
                    if (k == "appearance") put(k, rewrittenAppearance) else put(k, v)
                }
            }
        }
        val rewrittenAppearance = buildJsonObject {
            for ((k, v) in appearance) {
                if (k == "contentOverlays") continue
                put(k, v)
            }
            put("overlays", legacy)
        }
        return buildJsonObject {
            for ((k, v) in obj) {
                if (k == "appearance") put(k, rewrittenAppearance) else put(k, v)
            }
        }
    }
}
